### PR TITLE
Use new Queues as backend for Time Series constructs

### LINKED ISSUE #17: Time series and aggregation over time
So, Elixir / Erlang are high availability, so we could have a server with Beaker running for months / years without restart.

I've been playing locally and over time, the beaker_time_series_aggregator and beaker_time_series processes can grow to consume a lot of memory.  For example, after serving 60,000 requests, the beaker_time_series_aggregator is holding 13Mb of memory and beaker_time_series has 7.5Mb.

This seems to be because we keep everything.

I'm wondering if it's worth doing some work to limit the amount of data held permanently?  Something like a sliding window (http://blog.jonharrington.org/simple-sliding-windows-in-elixir/).  Seems like Erlang has us covered with `queue`.

What do you think?

### PR DESCRIPTION
**Pull request by hahuang65**
This fixes #17.

### CODE REVIEW

**Comment by hahuang65** [comment]
@mfeckie Looks like all the functionality is working. However, I'm not very happy that it's very steeply increased the time of aggregation (check out the failing tests).

I'm not sure what I want to do here.

**Comment by mfeckie** [comment]
@hahuang65 I've had a look through it and I don't have any ideas currently on how to improve the speed.  It did raise a question though, given that it only runs once per minute is this a 'deal breaker'?  Having said that, I'll ponder on it a bit more and let you know if I have any ideas :smile:

**Comment by hahuang65** [comment]
I don't think this is a dealbreaker right now. This is probably acceptable performance. Little sad though. :p

**Comment by hahuang65** [comment]
I'll change the tests so that they pass with the new numbers.

**Comment by hahuang65** [comment]
@mfeckie finally got around to tweaking those tests to allow more time.

**Comment by mfeckie** [comment]
Ship it.

I have a sense that it may not be such a big deal in real usage.  I noticed when poking around that thing were faster after the initial calculation and wonder if some of the 'slowness' is related to overhead of starting up the queue etc.

**Comment by hahuang65** [comment]
@mfeckie I updated the branch. Feel free to merge this PR whenever you're ready :)

**Pull request merged**
