### PR TITLE
Add size-bound and time-bound queue data structures

### PR DESCRIPTION
**Pull request by hahuang65**
This adds the data structures needed to implement https://github.com/hahuang65/beaker/issues/17

### CODE REVIEW

**Comment by hahuang65** [comment]
Lemme know what you think about this. I think this brings us a big step closer to replacing `Map` as a backend for `Beaker.TimeSeries.*`

**Comment by mfeckie** [comment]
Will take a good look later. First glance looks super interesting! I have the feeling I'm about to learn something cool!

**Comment by mfeckie** [comment]
@hahuang65 This looks good.  I'd be happy to see this merged.  Look forward to seeing how it affects memory usage :smile:

**Comment by hahuang65** [comment]
@mfeckie go ahead and merge it when you have a chance. I'll put up another PR to switch the Time Series backends to this.

**Pull request merged**
